[project]
name = "plated"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Adrian Vollmer", email = "av3@mailbox.org" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
plated = "plated:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
